{% set name = "gmaps" %}
{% set version = "0.5.3" %}
{% set sha256 = "56a146eaf97008307829703dfaf0db8759354b9143c10eca59c484c5eb660e1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter
  run:
    - python
    - ipywidgets >=6.0.0
    - geojson >=1.3.4

test:
  imports:
    - gmaps

about:
  home: http://github.com/pbugnion/gmaps
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Google maps for Jupyter notebooks'
  description: |
    gmaps is a Jupyter plugin for visualizing data on Google maps in Jupyter notebooks.
  doc_url: http://jupyter-gmaps.readthedocs.io/
  dev_url: https://github.com/pbugnion/gmaps

extra:
  recipe-maintainers:
    - pbugnion
