{% set name = "gmaps" %}
{% set version = "0.7.1" %}
{% set sha256 = "cea209a9794755a0c19def31e446c68aeb291ca7f3a826b484d6591dbb580844" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter
  run:
    - python
    - ipywidgets >=7.0.0
    - geojson >=2.0.0

test:
  imports:
    - gmaps

about:
  home: http://github.com/pbugnion/gmaps
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Google maps for Jupyter notebooks'
  description: |
    gmaps is a Jupyter plugin for visualizing data on Google maps in Jupyter notebooks.
  doc_url: http://jupyter-gmaps.readthedocs.io/
  dev_url: https://github.com/pbugnion/gmaps

extra:
  recipe-maintainers:
    - pbugnion
