{% set name = "gmaps" %}
{% set version = "0.9.0" %}
{% set sha256 = "e9a5a30e6537ce7bebff56f96484e1118ce2e784311b9d86f89a2eb02d0584f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - jupyter
  run:
    - python >=3.6
    - geojson >=2.0.0
    - ipywidgets >=7.0.0
    - jupyter

test:
  imports:
    - gmaps

about:
  home: http://github.com/pbugnion/gmaps
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Google maps for Jupyter notebooks'
  description: |
    gmaps is a Jupyter plugin for visualizing data on Google maps in Jupyter notebooks.
  doc_url: http://jupyter-gmaps.readthedocs.io/
  dev_url: https://github.com/pbugnion/gmaps

extra:
  recipe-maintainers:
    - pbugnion
