travis:
  secure:
    BINSTAR_TOKEN: jGyjJg82J42MiMayn2cAwcpMetn9RFA945C8/QhU9M3JGbo4wQ9Gzquu6HWi6x40rpmLmgpYkES0iH3p72TilWQyqTdyu/HgXO5stcebaERcLEUHAL5nkWlstAijLEnqBMFIhu8DVHcGcPJBrtlRsjq5jSA+nAG7FP5dGmLG1nNYxgOm+ohgIjGoDMYiyXf8P8y5kJVoebn9WXJxJliEIsMbX9F64lulWcQcY5sE6SsIL8uvEJv4mzWMEyYvgsDC/+yBd1PhuRaCe3RoB5zUbtgnYBAFa3m0yzQWM8Y8nqzzwCcW3WAGC79yirzm1er1g8/H2huuO50uDnhCCKYJ+qDHh6n6CpSea9NRx8z9CY789wfZyN41NHNsl3tuPs2uF6BaVPwhfvLpOSWcauaNdIwTDDoHQLZQJNwZiTYrFgxKuEm0nABnh2qICuevfHjHl+hsZ53lA0RfK+YYvZfrWA9To8K02nN6Nl8RF77KvIa52kLFHDbGl/U2w0yCcWmrIm3l0Go3FAqFTM/Jw/2N0yP47dmN+8F1MDgXTr5xrOy8B0QbrKYN+Qr9f/9UwfG2AmcFH2dTTnOqc0DrQV9Cjo8IBRTlqNrPiBy3zhoS+EE2KtRPnFPTLPHp3THzKoTB59Fe2sEymmPOrQNGLQX7tB6waAKPS+oSNkVDJobtpWE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
