travis:
  secure:
    BINSTAR_TOKEN: S/OtzEYWX875uFVEC/hH9xo5SB4dMXu5NgLM7woSCeQg824z08OjlUkEs3PKyQTFwYZWcP+xXklFxvnfPH6wbEStJSZr9v1BjtKOMxmYdbfUnGsFsyNpeYaqbDMCIL40dxQUhaFvkXWI9D7nOgsK+ux8ffVQSlQePLJc5+P1veSlblFwNHu0KzL36xL2Z1KtRtHdqpt807f7h5vuw/lhIn+3dBzD5GjgMxZA13DXwYmQbeQIHvTiyVZo0EtTgcfZzJRUh1GDl/mkPoXafdrKGs6OF09ZBZ5/l8HTqjW34SERCx6R6b7hkWkSIGjhnyP0lO4tx+CEUpksjxHF/Flc3OQv/Py6oXrdY3XkmwB0DINUp3/iQZJEDbHI7OEvqGiQW/XRcnR9OoYKLX9wYwWAYk5xKuL6pFxcPwn5mTkb2y0ZdG5EQce6KNP8bEL8qugFlSFg25P7qWR1AhP2OyxXd/O5XXDgLTknKoyDgQfTf64b7LZDBbveaGvA4J/QrSSGHYkoUdN70A6dQqu7tkqBeuOwzdlZ1Rbceskq5WE3hXojb4jqbwE+z77g3yS2d0G/HQFQowZk129yMn2qmffzMXJ9SQipNYefU1OdtlL9gr3EkRRQgDwNO28YeaCeYihJbplhdIwr2D8GID/eAdkFbbmmovEnLYXIBcMSaVHbn8w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
